stages:
  - build
  - test
  - deploy
#Build Stage
build-job:
  stage: build
  script:
    - echo "Building the project..."
#Test Stage
test-job:
  stage: test
  script:
    - echo "Running tests..."
    - echo "All tests passed!"
#Deploy Stage
deploy-job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - echo "Deployment complete!"
